// Widgets
import "./widgets/timeDate.js";
import "./widgets/systemVolume.js";
import "./widgets/weather.js";
import "./widgets/notepad.js";
import "./widgets/clipboard.js";
import "./widgets/stopwatch.js";
import "./widgets/performance.js";
import "./widgets/screenRecorder.js";
